on:
  push:

jobs:
  hello-tacos:
    runs-on: ubuntu-latest
    name: Compiles and deploys the counter.jsligo contract to a local sandbox
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install modules
        run: |
          cd hello-tacos
          npm update

      - name: compile contracts
        uses: ./
        with:
          project_directory: 'hello-tacos'
          compile_command: 'compile'

      - name: start local sandbox
        uses: ./
        with:
          project_directory: 'hello-tacos'
          sandbox_name: 'local'

      - name: originate contracts
        uses: ./
        with:
          project_directory: 'hello-tacos'
          originate: True

      - name: run tests
        uses: ./
        with:
          project_directory: 'hello-tacos'
          tests: True